version: "3.5"

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "9876:5432"
      - "9999:8181"
    volumes:
      - postgres-data1:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  pgadmin:
    container_name: pgadmin4_
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5555:80"

  redis:
      image: redis:latest
      container_name: redis_server
      volumes:
         - '/data/2021/backups/dvolumes/bwb/docker-redis:/data'
      ports:
         - '6379:6379'
      restart: always
      healthcheck:
         test: ['CMD', 'redis-cli', 'ping']
         interval: 30s
         timeout: 10s
         retries: 3


volumes:
  postgres-data1: